# Generated by Django 3.1.5 on 2021-01-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalshop', '0004_delete_somemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartphone',
            name='sd_volume',
        ),
        migrations.AddField(
            model_name='cart',
            name='for_anonymous_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='in_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='sd_volume_max',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Максимальный объём встраиваемой памяти'),
        ),
    ]
