# Generated by Django 3.1.5 on 2021-01-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalshop', '0005_auto_20210119_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphone',
            name='sd',
            field=models.BooleanField(default=True, verbose_name='Наличие SD карты'),
        ),
    ]
