# Generated by Django 3.1.5 on 2021-01-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalshop', '0006_auto_20210119_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
    ]
