# Generated by Django 3.1.5 on 2021-01-21 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicalshop', '0007_auto_20210120_2357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='total_product',
            new_name='total_products',
        ),
        migrations.AlterField(
            model_name='cart',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Общая цена'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicalshop.customer', verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='related_cart', to='medicalshop.CartProduct'),
        ),
    ]
